version: '3'

services:
  app:
    container_name: no-cors
    image: no-cors
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - .:/app
      - /app/node_modules
